<?php
// module/Album/view/album/album/index.phtml:

$displayName = $this->lmcUserDisplayName();

$title = $displayName . '\'s albums';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$userIdentity = $this->lmcUserIdentity();
$usermail = $userIdentity->getEmail();
?>
<p>
    <a href="<?= $this->url('album', ['action' => 'add']) ?>">Add new album</a>
</p>
<p>
    <a href="<?= $this->url('album', ['action' => 'show']) ?>">My Albums</a>
</p>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($albums as $album) : ?>
        <tr>
            <td><?= $this->escapeHtml($album->title) ?></td>
            <td><?= $this->escapeHtml($album->artist) ?></td>
            <td><?= $this->escapeHtml($album->outyear) ?></td>
            <td>
                <?php if ($album->user_email === $usermail) { ?>
                    <a href="<?= $this->url('album', ['action' => 'edit', 'id' => $album->id]) ?>">Edit</a>
                    <a href="<?= $this->url('album', ['action' => 'delete', 'id' => $album->id]) ?>">Delete</a>
                <?php } ?>
            </td>
        </tr>
    <?php endforeach; ?>
</table>