<?php
$title = 'Louc Meteo';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<h2> Temps actuel à <?= $meteo->getCityInfo()->name ?> : <img src="<?= $meteo->getCurrentCondition()->icon_big ?>"></h2> 

<table class="table">
    <tr >
        <th><h4>Heure</h4></th>
        <th><h4>Condition</h4></th>
        <th><h4>Temperature</h4></th>
        <th><h4>Vent</h4></th>
        <th><h4>Pluie</h4></th>
    </tr>
</thead>
<tbody >

    <tr>
        <td>9h00</td>
        <td><img src="<?= $meteo->getDayDetails()->hourly_data->{'9H00'}->ICON ?>"></td>
        <td ><?= $meteo->getDayDetails()->hourly_data->{'9H00'}->TMP2m ?> °C</td>
        <td ><?= $meteo->getDayDetails()->hourly_data->{'9H00'}->WNDSPD10m ?> Km/H</td>
        <td ><?= $meteo->getDayDetails()->hourly_data->{'9H00'}->APCPsfc ?> mm</td>
    </tr>

    <tr>
        <td>12h00</td>
        <td><img src="<?= $meteo->getDayDetails()->hourly_data->{'12H00'}->ICON ?>"></td>
        <td ><?= $meteo->getDayDetails()->hourly_data->{'12H00'}->TMP2m ?> °C</td>
        <td ><?= $meteo->getDayDetails()->hourly_data->{'12H00'}->WNDSPD10m ?> Km/H</td>
        <td ><?= $meteo->getDayDetails()->hourly_data->{'12H00'}->APCPsfc ?> mm</td>
    </tr>

    <tr>
        <td>17h00</td>
        <td><img src="<?= $meteo->getDayDetails()->hourly_data->{'17H00'}->ICON ?>"></td>
        <td ><?= $meteo->getDayDetails()->hourly_data->{'17H00'}->TMP2m ?> °C</td>
        <td ><?= $meteo->getDayDetails()->hourly_data->{'17H00'}->WNDSPD10m ?> Km/H</td>
        <td ><?= $meteo->getDayDetails()->hourly_data->{'17H00'}->APCPsfc ?> mm</td>
    </tr>

    <tr>
        <td>21h00</td>
        <td><img src="<?= $meteo->getDayDetails()->hourly_data->{'21H00'}->ICON ?>"></td>
        <td ><?= $meteo->getDayDetails()->hourly_data->{'21H00'}->TMP2m ?> °C</td>
        <td ><?= $meteo->getDayDetails()->hourly_data->{'21H00'}->WNDSPD10m ?> Km/H</td>
        <td ><?= $meteo->getDayDetails()->hourly_data->{'21H00'}->APCPsfc ?> mm</td>
    </tr>

</tbody>
</table>

<?php
// This provides a default CSS class and placeholder text for the title element:
$album = $form->get('city');
$album->setAttribute('class', 'form-control');
$album->setAttribute('placeholder', 'Chercher une ville');

// This provides a default CSS class and placeholder text for the artist element:
// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('meteo', ['action' => 'city']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
// label, element, and errors separately within 
?>
<div class="form-group">
<?= $this->formLabel($album) ?>
<?= $this->formElement($album) ?>
<?= $this->formElementErrors()->render($album, ['class' => 'help-block']) ?>
</div>

<div class="form-group">

</div>
<br>
<?php
echo $this->formSubmit($submit);
echo $this->form()->closeTag();
?>
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

<div id="myPlot" ></div>

<script>
    const xArray = [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 23];
    const yArray = [<?= $meteo->getDayDetails()->hourly_data->{'0H00'}->TMP2m ?>, <?= $meteo->getDayDetails()->hourly_data->{'2H00'}->TMP2m ?>, <?= $meteo->getDayDetails()->hourly_data->{'4H00'}->TMP2m ?>, <?= $meteo->getDayDetails()->hourly_data->{'6H00'}->TMP2m ?>, <?= $meteo->getDayDetails()->hourly_data->{'8H00'}->TMP2m ?>, <?= $meteo->getDayDetails()->hourly_data->{'10H00'}->TMP2m ?>, <?= $meteo->getDayDetails()->hourly_data->{'12H00'}->TMP2m ?>, <?= $meteo->getDayDetails()->hourly_data->{'14H00'}->TMP2m ?>, <?= $meteo->getDayDetails()->hourly_data->{'16H00'}->TMP2m ?>, <?= $meteo->getDayDetails()->hourly_data->{'18H00'}->TMP2m ?>, <?= $meteo->getDayDetails()->hourly_data->{'20H00'}->TMP2m ?>, <?= $meteo->getDayDetails()->hourly_data->{'22H00'}->TMP2m ?>, <?= $meteo->getDayDetails()->hourly_data->{'23H00'}->TMP2m ?>];

// Define Data
    const data = [{
            x: xArray,
            y: yArray,
            mode: "line"
        }];

// Define Layout
    const layout = {
        xaxis: {range: [0, 23], title: "Heure"},
        yaxis: {range: [<?= $meteo->getDayDetails()->tmin ?>-1, <?= $meteo->getDayDetails()->tmax ?>+1], title: "Temperature"},
        title: "Graphique pour le <?= $meteo->getDayDetails()->day_short ?> <?= $meteo->getDayDetails()->date ?> à <?= $meteo->getCityInfo()->name ?>"
    };

// Display using Plotly
    Plotly.newPlot("myPlot", data, layout);
</script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
<body>
<canvas id="myChart" style="width:100%;max-width:600px"></canvas>
