<?php
$title = 'Louc Meteo';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<h2> Temps actuel à <?= $meteo->getCityInfo()->name ?> : <img src="<?= $meteo->getCurrentCondition()->icon_big ?>"></h2> 

<table class="table">
    <tr >
        <th><h4>Heure</h4></th>
        <th><h4>Condition</h4></th>
        <th><h4>Temperature</h4></th>
        <th><h4>Vent</h4></th>
        <th><h4>Pluie</h4></th>
    </tr>
</thead>
<tbody >

    <tr>
        <td>9h00</td>
        <td><img src="<?= $meteo->getDayDetails()->hourly_data->{'9H00'}->ICON ?>"></td>
        <td ><?= $meteo->getDayDetails()->hourly_data->{'9H00'}->TMP2m ?> °C</td>
        <td ><?= $meteo->getDayDetails()->hourly_data->{'9H00'}->WNDSPD10m ?> Km/H</td>
        <td ><?= $meteo->getDayDetails()->hourly_data->{'9H00'}->APCPsfc ?> mm</td>
    </tr>

    <tr>
        <td>12h00</td>
        <td><img src="<?= $meteo->getDayDetails()->hourly_data->{'12H00'}->ICON ?>"></td>
        <td ><?= $meteo->getDayDetails()->hourly_data->{'12H00'}->TMP2m ?> °C</td>
        <td ><?= $meteo->getDayDetails()->hourly_data->{'12H00'}->WNDSPD10m ?> Km/H</td>
        <td ><?= $meteo->getDayDetails()->hourly_data->{'12H00'}->APCPsfc ?> mm</td>
    </tr>

    <tr>
        <td>17h00</td>
        <td><img src="<?= $meteo->getDayDetails()->hourly_data->{'17H00'}->ICON ?>"></td>
        <td ><?= $meteo->getDayDetails()->hourly_data->{'17H00'}->TMP2m ?> °C</td>
        <td ><?= $meteo->getDayDetails()->hourly_data->{'17H00'}->WNDSPD10m ?> Km/H</td>
        <td ><?= $meteo->getDayDetails()->hourly_data->{'17H00'}->APCPsfc ?> mm</td>
    </tr>

    <tr>
        <td>21h00</td>
        <td><img src="<?= $meteo->getDayDetails()->hourly_data->{'21H00'}->ICON ?>"></td>
        <td ><?= $meteo->getDayDetails()->hourly_data->{'21H00'}->TMP2m ?> °C</td>
        <td ><?= $meteo->getDayDetails()->hourly_data->{'21H00'}->WNDSPD10m ?> Km/H</td>
        <td ><?= $meteo->getDayDetails()->hourly_data->{'21H00'}->APCPsfc ?> mm</td>
    </tr>

</tbody>
</table>
<?php



?>

<?php
// This provides a default CSS class and placeholder text for the title element:
$album = $form->get('city');
$album->setAttribute('class', 'form-control');
$album->setAttribute('placeholder', 'Chercher une ville');

// This provides a default CSS class and placeholder text for the artist element:



// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

#$form->setAttribute('action', $this->url('meteo', ['action' => 'city']));
#$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($album) ?>
    <?= $this->formElement($album) ?>
    <?= $this->formElementErrors()->render($album, ['class' => 'help-block']) ?>
</div>

<div class="form-group">

</div>
<br>
<?php
echo $this->formSubmit($submit);
echo $this->form()->closeTag();